### PR TITLE
Added Rule Validation Support

### PR DESCRIPTION
**Pull request by ShankarParimi**
- Introduced jsonlogic.validate method to validate the rules

### CODE REVIEW

**Comment by the729** [comment]
Good idea. But I won't be able to merge if you changed the package into your namespace.

**Comment by ShankarParimi** [comment]
> Good idea. But I won't be able to merge if you changed the package into your namespace.

reverted the package imports.

**Comment by the729** [comment]
Please also revert the badge links in readme.md. 

BTW, you could use "replace" in go.mod so that you don't have to change the import path in the first place. https://golang.org/doc/modules/gomod-ref#replace

**Comment by ShankarParimi** [comment]
> Please also revert the badge links in readme.md.
> 
> BTW, you could use "replace" in go.mod so that you don't have to change the import path in the first place. https://golang.org/doc/modules/gomod-ref#replace

Made relevant changes. please review

**Comment by ShankarParimi** [comment]
Can you please release new version for this change? @the729

**Comment by the729** [comment]
released v0.2.0

**Pull request merged**
